version: "3"
services:
  npm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    env_file:
      - .env
  forge:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/forge
    volumes:
      - .:/src
    env_file:
      - .env
