version: "3"
services:
  npm:
    image: node:12-alpine
    volumes:
      - .:/src
    env_file:
      - .env

    entrypoint: npm
    working_dir: /src
  forge:
    image: stormforger/cli
    volumes:
      - .:/src
    env_file:
      - .env
