"use strict";

import gulp from "gulp";
import concat from "gulp-concat";
import insert from "gulp-inject-string";

function getBanner() {
  return `// generated at ${Date()}
//
// This file is automatically generated.
//
// (!!!) DO NOT MODIFY DIRECTLY! (!!!)
//\n\n`
}

function getFooter() { return "" }

exports.default = gulp.task("default", () => {
  return gulp.src([
      "./cases/acme-shop/setup.js",
      "./cases/acme-shop/scenarios/*.js",
      "./cases/acme-shop/debugging_scenario.js",
      "./components/*.js",
    ], {})
    .pipe(concat("acme-shop.js"))
    .pipe(insert.wrap(getBanner(), getFooter()))
    .pipe(gulp.dest("./dist"));
});
